version: '2.1'
services:
  app:
    build: .
    depends_on:
      - db
    volumes:
      - '.:/service'
  db:
    image: postgres:11
    ports:
      - 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root"]
      interval: 10s
      timeout: 5s
      retries: 10
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    volumes:
      - ./db/init.d:/docker-entrypoint-initdb.d/
